### ISSUE TITLE
OpenAPI Generator users list

### ISSUE THREAD

**Issue by ackintosh** [jenkins-x/jx-ts-client#19]
Hi,

I'm glad to find out that this project is using OpenAPI Generator. ✨ 

If you don't mind, could we add this project (Jenkins X) to the user list?

https://openapi-generator.tech/users.html

Thank you,

Core team and founding member of OpenAPI Generator
Akihito Nakano

**Comment by ackintosh** [comment]
cc: @pmuir 😉

**Comment by pmuir** [comment]
Please do.
